version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    # environment:
    #   IMAGE: cv
    #   TAG: test
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build cv image
          command: make build
      - run:
          name: Tag cv image
          command: make tag
      - run:
          name: Push cv image
          command: make push
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
